### ISSUE TITLE
Provide a better example than Example-2.yml

### ISSUE THREAD

**Issue by tomkerkhove** [oam-dev/oam-dev.github.io#13]
Current `Example-2.yml` is not that ideal as it uses things like `foo`, `bar`, `UNUSED` which makes it hard to grasp the power of OAM.

```yaml
apiVersion: core.oam.dev/v1alpha1
kind: ComponentSchematic
metadata:
  name: alpine-forever-v1
spec:
  workloadType: core.oam.dev/v1alpha1.SingletonServer
  parameters:
    - name: message
      type: string
      required: false
    - name: unused_integer
      type: number
      required: false
      default: 5678
  containers:
    - name: runner
      image: technosophos/alpine-forever:latest
      env:
        - name: FOO
          value: bar
          fromParam: message
        - name: UNUSED
          value: "1234"
          fromParam: unused_integer
```

Would it make sense if we replace this with another sample or use more representing values?
